### ISSUE TITLE
Publish the latest Nyan update 2.0.4 to F-Droid

### ISSUE THREAD

**Issue by Nickoriginal** [powerje/NyanDroid#9]
Here is my video: app instantly crashes and requires "clear data".

<details>

https://user-images.githubusercontent.com/85299944/148673887-5b3af7c5-c16d-4e42-8e9f-b01ff1f541bb.mp4
</details>
Samsung Galaxy A20s, Android 11, build A207FXXU2CUI2

**Comment by Nickoriginal** [comment]
It is fixed in 2.0.4, but I am using F-droid version (the last is 2.0.3). Would be good to distribute this update there.

**Comment by powerje** [comment]
Apologies, I saw this, didn't have time to reply, and promptly forgot about it!

F-Droid actually builds this app themselves and publishes it, I'm not sure what happened there. @dalb8 did the initial work to get it published there - @dalb8, any idea how to get the latest update on F-Droid? I'm not sure how that process works.

**Comment by powerje** [comment]
I think it never got to f-droid because I never published 2.0.4 on GitHub, hopefully f-droid picks up the new release (https://github.com/powerje/NyanDroid/releases/tag/2.0.4)

**Comment by Nickoriginal** [comment]
It was published in F-Droid right now! This and other issues are resolved. Thanks!
<img src=https://user-images.githubusercontent.com/85299944/159979499-74490953-17ea-4d23-a593-62165daf548a.png width=50%>
